# Generated by Django 4.2.1 on 2023-06-30 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images'),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='Sin titulo', max_length=255),
            preserve_default=False,
        ),
    ]
